# Generated by Django 5.0.6 on 2024-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.TextField(default='Developer'),
            preserve_default=False,
        ),
    ]
