# Generated by Django 5.0.6 on 2024-06-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0003_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
