# Generated by Django 5.0.6 on 2024-06-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social_media', '0006_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
